# Automatic manual QA
When making changes to the page itself it's good to know that current files still work. That's why this notebook automatically renders some examples to verify that everything is still fine. 

In [1]:
import IPython
import json
import base64
import numpy as np

# No input to the URL
Should display a nice example of what can be achieved

In [4]:
url = 'http://127.0.0.1:8000/oculus.html'
iframe = '<iframe src=' + url + ' width=1000 height=550></iframe>'
IPython.display.HTML(iframe)

# Set name to XYZ RGB file
Should show a pointcloud with XYZ RGB points

In [5]:
url = 'http://127.0.0.1:8000/oculus.html?name=236bcdf2-0376-4b8b-b76b-c15e58e75ecc.xyzrgb'
iframe = '<iframe src=' + url + ' width=1000 height=550></iframe>'
IPython.display.HTML(iframe)

# Input a JSON file with XYZI file
Should show a pointcloud with XYZ with intensity points

In [6]:
todisplay = {
    "points": [
        {
            "source": "url",
            "url": "https://pointcloudvisualization.s3.eu-central-1.amazonaws.com/e2652aab-4ace-4a09-86f4-374b23cb677b.xyzi",
            "type": "XYZI",
        }
    ]
}

data = json.dumps(todisplay)
data = base64.urlsafe_b64encode(json.dumps(todisplay).encode())

url = 'http://127.0.0.1:8000/oculus.html?jsonb64=' + data.decode('ascii')
iframe = '<iframe src=' + url + ' width=1000 height=550></iframe>'
IPython.display.HTML(iframe)


# Input a JSON file with Base64 XYZI points
Should show a pointcloud with XYZ with intensity points

In [7]:
randompoints = np.random.rand(250,4)

swapped_bytes = randompoints.astype(np.float32).byteswap()
base_64_string = base64.b64encode(swapped_bytes)


todisplay = {
    "points": [
        {
            "source": "base64",
            "base64": str(base_64_string)[2:-1],
            "type": "XYZI"
        }
    ]
}

data = json.dumps(todisplay)
data = base64.urlsafe_b64encode(json.dumps(todisplay).encode())

url = 'http://127.0.0.1:8000/oculus.html?jsonb64=' + data.decode('ascii')
# print(url)
iframe = '<iframe src=' + url + ' width=1000 height=550></iframe>'
IPython.display.HTML(iframe)

In [8]:
randompoints = np.random.rand(250,4)

swapped_bytes = randompoints.astype(np.float32).byteswap()
base_64_string = base64.b64encode(swapped_bytes)


todisplay = {
    "points": [
        {
            "source": "url",
            "url": "https://pointcloudvisualization.s3.eu-central-1.amazonaws.com/cars5.xyzi",
            "type": "XYZI"
        }
    ],
    "bboxes": [
        {     
            "source": "url",
            "url": "https://pointcloudvisualization.s3.eu-central-1.amazonaws.com/cars5boxes.npy"
        }
    ]
}

data = json.dumps(todisplay)
data = base64.urlsafe_b64encode(json.dumps(todisplay).encode())

url = 'http://127.0.0.1:8000/oculus.html?jsonb64=' + data.decode('ascii')
print(url)
iframe = '<iframe src=' + url + ' width=1000 height=550></iframe>'
IPython.display.HTML(iframe)

http://127.0.0.1:8000/oculus.html?jsonb64=eyJwb2ludHMiOiBbeyJzb3VyY2UiOiAidXJsIiwgInVybCI6ICJodHRwczovL3BvaW50Y2xvdWR2aXN1YWxpemF0aW9uLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL2NhcnM1Lnh5emkiLCAidHlwZSI6ICJYWVpJIn1dLCAiYmJveGVzIjogW3sic291cmNlIjogInVybCIsICJ1cmwiOiAiaHR0cHM6Ly9wb2ludGNsb3VkdmlzdWFsaXphdGlvbi5zMy5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS9jYXJzNWJveGVzLm5weSJ9XX0=


In [16]:
lines = list()
lines.append([0,0,0,0,0,2])
lines.append([0,0,0,0,1,0])
lines.append([0,0,0,1,0,0])
lines = np.array(lines, dtype=np.float32)
print(lines)
lines.byteswap().tofile('lines.lines')

randompoints = np.random.rand(250,4)

swapped_bytes = randompoints.astype(np.float32).byteswap()
base_64_string = base64.b64encode(swapped_bytes)


todisplay = {
    "points": [
        {
            "source": "url",
            "url": "https://pointcloudvisualization.s3.eu-central-1.amazonaws.com/cars5.xyzi",
            "type": "XYZI"
        }
    ],
    "lines": [
        {
            "source": "url",
            "url": "lines.lines"
        }
    ],
}

data = json.dumps(todisplay)
data = base64.urlsafe_b64encode(json.dumps(todisplay).encode())

url = 'http://127.0.0.1:8000/oculus.html?jsonb64=' + data.decode('ascii')
print(url)
iframe = '<iframe src=' + url + ' width=1000 height=550></iframe>'
IPython.display.HTML(iframe)

[[0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]]
http://127.0.0.1:8000/oculus.html?jsonb64=eyJwb2ludHMiOiBbeyJzb3VyY2UiOiAidXJsIiwgInVybCI6ICJodHRwczovL3BvaW50Y2xvdWR2aXN1YWxpemF0aW9uLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL2NhcnM1Lnh5emkiLCAidHlwZSI6ICJYWVpJIn1dLCAibGluZXMiOiBbeyJzb3VyY2UiOiAidXJsIiwgInVybCI6ICJsaW5lcy5saW5lcyJ9XX0=


In [7]:
# 3D objects

In [9]:
todisplay = {
    "points": [
        {
            "source": "url",
            "url": "https://pointcloudvisualization.s3.eu-central-1.amazonaws.com/e2652aab-4ace-4a09-86f4-374b23cb677b.xyzi",
            "type": "XYZI",
        }
    ], 
    "objects": [
        {
            "source": "url", 
            "url": "honda.glb", 
            "position": [1.0, 2.0, 3.0], 
            "rotation": [0.0, -1.55, 0.0], 
            "scale": [0.1, 0.1, 0.1], 
        }
    ]
}

data = json.dumps(todisplay)
data = base64.urlsafe_b64encode(json.dumps(todisplay).encode())

url = 'http://127.0.0.1:8000/oculus.html?jsonb64=' + data.decode('ascii')
print(url)
iframe = '<iframe src=' + url + ' width=1000 height=550></iframe>'
IPython.display.HTML(iframe)


http://127.0.0.1:8000/oculus.html?jsonb64=eyJwb2ludHMiOiBbeyJzb3VyY2UiOiAidXJsIiwgInVybCI6ICJodHRwczovL3BvaW50Y2xvdWR2aXN1YWxpemF0aW9uLnMzLmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL2UyNjUyYWFiLTRhY2UtNGEwOS04NmY0LTM3NGIyM2NiNjc3Yi54eXppIiwgInR5cGUiOiAiWFlaSSJ9XSwgIm9iamVjdHMiOiBbeyJzb3VyY2UiOiAidXJsIiwgInVybCI6ICJob25kYS5nbGIiLCAicG9zaXRpb24iOiBbMS4wLCAyLjAsIDMuMF0sICJyb3RhdGlvbiI6IFswLjAsIC0xLjU1LCAwLjBdLCAic2NhbGUiOiBbMC4xLCAwLjEsIDAuMV19XX0=
